apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-wp
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/www/html
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-mysql
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/mysql
