apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 8.3.3
  nodeSets:
  - name: esdata
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          kubernetes.io/hostname: node-1
        volumes:
        - name: elasticsearch-data
          emptyDir: {}
